[source.crates-io]
replace-with = 'tuna-sparse'

[source.tuna-sparse]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

# 网络设置
[net]
retry = 5
git-fetch-with-cli = true

# HTTP设置
[http]
check-revoke = false
timeout = 60

[http.ssl-version]
min = "tlsv1.2"
